# Plugins
gems:
    - jekyll-paginate
    - jekyll-asciidoc
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:          pretty

# Setup
title:              Hardbits
tagline:            making hard bits softer
description:        adventures in making hardware and software
url:                https://blog.chrylis.com
paginate:           5
paginate_path:      "page/:num"
baseurl:            ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
exclude:
    - vendor
    
sass:
  sass_dir:         _sass
  style:            :compressed

# About/contact
author:
  name:             Christopher Smith
  url:              https://twitter.com/chrylis
  email:            chrylis@gmail.com

# Custom vars
version:            2.0.0
github:
  repo:             https://github.com/chrylis/chrylis.github.io

highlighter:        coderay
timezone:           America/Central

asciidoctor:
    attributes:
        - icons=font
        - source-highlighter=coderay
        - coderay-css=style
